# Generated by Django 2.1.5 on 2019-01-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190131_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
